bookings/urls.py
from django.urls import path
# from .views import CreateBooking
from .views import createBooking,bookingHistory,cancelBooking,book_flight,flightbookingHistory,cancelFlightBooking

app_name = "booking"

urlpatterns = [
    # path("booking/<int:hotelid>", CreateBooking.as_view(), name="create_booking"),
    path("booking/<int:hotelid>", createBooking, name="create_booking"),
    path("booking-history/<int:userid>", bookingHistory, name="booking_history"),
    path("cancel-booking/", cancelBooking, name="cancel_booking"),
     path("book-flight/", book_flight, name="book_flight"),
     path("flight-booking-history/<int:userid>", flightbookingHistory, name="flight_booking_history"),
    path("cancel-flight-booking/", cancelFlightBooking, name="cancel_flight_booking"),

    ]

hotel/urls.py
from django.urls import path
from hotel.views import homepage_view, hotel_detail_view, search_view,sort_hotel,termsandconditions

app_name = "hotel"

urlpatterns = [
    path("", homepage_view, name="homepage"),
    path("search/", search_view, name="searchhotel"),
    path("hotel/<int:hotelid>/", hotel_detail_view, name="hotel_detail"),
    path("terms-and-condition",termsandconditions,name="terms"),
    path('sort-hotels/', sort_hotel, name='sort_hotel')
]

travelsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("site/admin/", admin.site.urls),
    path("", include("hotel.urls", namespace="hotel")),
    path("", include("flight.urls", namespace="flight")),
    path("", include("payment.urls", namespace="payment")),

    path("", include("bookings.urls", namespace="booking")),
    path("", include("useraccount.urls", namespace="user")),
    path("", include("client.urls", namespace="client")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Travel Admin"
admin.site.site_title = " Travel Portal"
admin.site.index_title = "Welcome to Travel Admin Portal"

useraccount/urls.py
from django.urls import path
from useraccount.views import UserLoginView, SignupView, user_profile, user_profile_edit,make_client,makeclientpage,password_change
from django.contrib.auth.views import LogoutView

app_name = "user"
urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", SignupView.as_view(), name="register"),
    path("profile/<user>/userid=<int:id>/", user_profile, name="userprofile"),
    path("profile-edit/<int:id>", user_profile_edit, name="edit_profile"),
    path(r'^password/$', password_change, name='change_password'),
    # path("password-change/<int:id>", password_change, name="change_password"),
    path("makeclient/", make_client, name="make_client"),
    path("becomeclient/", makeclientpage, name="make_client_page"),
]

useraccount/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    address = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)
    image = models.ImageField(upload_to="userimages", blank=True, null=True)
    stripe_session=models.CharField(max_length=500,null=True,blank=True)
    is_client = models.BooleanField(default=False)
    stripe_customer_id=models.CharField(max_length=500,null=True,blank=True)

useraccount/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator
from django import forms

User = get_user_model()


class UserSignupForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=50,
        validators=[RegexValidator(r"^[a-zA-Z]+$")],
        error_messages={"invalid": "Name can only contain alphabets a-z or A-Z"},
    )
    last_name = forms.CharField(
        max_length=50,
        validators=[RegexValidator(r"^[a-zA-Z]+$")],
        error_messages={"invalid": "Name can only contain alphabets a-z or A-Z"},
    )
    phone = forms.CharField(
        max_length=100,
        validators=[RegexValidator(r"^[0-9]+$")],
        error_messages={"invalid": "Phone Number can only be Numbers 0-9"},
    )
    email = forms.CharField(
        max_length=100,
        error_messages={"invalid": "Invalid Email! Please insert a valid Email"},
    )
    address = forms.CharField(
        max_length=100,
        validators=[RegexValidator(r"^[a-zA-Z0-9_.-]*$")],
        error_messages={"invalid": "Please insert a valid Address"},
    )

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "email",
            "username",
            "address",
            "phone",
            "image",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields["name"].widget.attrs["class"] = "form-control"   this is used to customize single field
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
class PasswordChangeForm(forms.ModelForm):
    class Meta:
        model=User
        fields = ("__all__")
        
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
        # self.fields["name"].widget.attrs["class"] = "form-control"   this is used to customize single field
            for visible in self.visible_fields():
                visible.field.widget.attrs["class"] = "form-control"



class UserEditForm(forms.ModelForm):
    first_name = forms.CharField(
        max_length=50,
        validators=[RegexValidator(r"^[a-zA-Z]+$")],
        error_messages={"invalid": "Name can only contain alphabets a-z or A-Z"},
    )
    last_name = forms.CharField(
        max_length=50,
        validators=[RegexValidator(r"^[a-zA-Z]+$")],
        error_messages={"invalid": "Name can only contain alphabets a-z or A-Z"},
    )
    phone = forms.CharField(
        max_length=100,
        validators=[RegexValidator(r"^[0-9]+$")],
        error_messages={"invalid": "Phone Number can only be Numbers 0-9"},
    )
    email = forms.CharField(
        max_length=100,
        error_messages={"invalid": "Invalid Email! Please insert a valid Email"},
    )

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "email",
            "username",
            "address",
            "phone",
            "image",
        )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields["name"].widget.attrs["class"] = "form-control"   this is used to customize single field
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

useraccount/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth.views import LoginView
from django.views.generic import CreateView
from django.contrib.auth import get_user_model
from useraccount.forms import UserSignupForm, UserEditForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.conf import settings
from django.contrib import messages 

import stripe
stripe.api_key = "sk_test_51N2DKlBDe5c2rfDAZlaYAUJWD6ORem7RLEZFoDAZcKyPx55mSltZ2L2KrgeHboSO7hr7pSzcO1OpvGVhdosoeEDW00VrQx4XTO"


# Create your views here.

User = get_user_model()


class UserLoginView(LoginView):
    template_name = "login.html"
    redirect_authenticated_user = True
    success_url = reverse_lazy("hotel:homepage")


class SignupView(CreateView):
    model = User
    form_class = UserSignupForm
    template_name = "register.html"
    success_url = reverse_lazy("hotel:homepage")
    # def get(self,request):
    #     if request.user.is_authenticated:
    #         print(request.user)
    #         return HttpResponseRedirect( reverse(
    #             "hotel:homepage")
    #         )
        # else:
        #     return render(request,"register.html")
    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.save()
        return super().form_valid(form)
   
           


@login_required
def user_profile(request, user, id):
    user = get_object_or_404(User, username=user, id=id)
    userss = UserEditForm(request.POST or None, request.FILES or None, instance=user)

    return render(
        request,
        "profile.html",
        {"users": user, "userprofile": userss,},
    )


@login_required
def user_profile_edit(request, id):
    user = get_object_or_404(User, id=id, username=request.user)
    userss = UserEditForm(request.POST or None, request.FILES or None, instance=user)
    if userss.is_valid():
        userss.save()

        return HttpResponseRedirect(
            reverse(
                "user:userprofile",
                args=(
                    user.username,
                    user.id,
                ),
            )
        )

    return render(request, "profile_edit.html", {"userprofile": userss})
@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            # return redirect('user:userprofile')
            return HttpResponseRedirect(
            reverse(
                "user:userprofile",
                args=(
                    user.username,
                    user.id,
                ),
            )
        )
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'changepassword.html', {
        'form': form
    })
# @login_required
# def password_change(request,id):
#     user=get_object_or_404(User,id=id,username=request.user)
#     userform=PasswordChangeForm(request.POST or None,request.FILES or None)
#     if userform.is_valid():
#         userform.save()
#         return HttpResponseRedirect(
#             reverse(
#                 "user:userprofile",
#                 args=(
#                     user.username,
#                     user.id,
#                 ),
#             )
#         )

#     return render(request, "changepassword.html", {"userprofile": userform})



def makeclientpage(request):
    return render(request, "become_client.html")

@login_required
def make_client(request):
    user=User.objects.get(id=request.user.id)
    if user.stripe_customer_id is None:
        acount=stripe.Account.create(type="express")
        user.stripe_customer_id=acount.id
        user.is_client=True
        user.save()
    else:
        acount = stripe.Account.retrieve(user.stripe_customer_id)

    account_link=stripe.AccountLink.create(
        account=acount.id,
        refresh_url="https://www.google.com/",
        return_url=settings.REDIRECT_DOMAIN,
        type="account_onboarding",
        )
    return render(request, "become_client.html", {"account_link_url": account_link.url, "user": user})

useraccount/templates/become_client.html
{% extends 'base_site.html' %} {% block maincontent %}
<div
  class="container mt-4 mb-4 p-3 d-flex justify-content-center mh-100"
  style="height: 400px"
>
  {% if user.stripe_customer_id %}
  <p>You are already our client</p>

  {% else %}
  <h2>Click the link to create a connected account-></h2>

  <h2>
    <a href="{{ account_link_url }}" class="text-primary" target="_blank"
      >Create Account</a
    >
  </h2>
  {% endif %}
</div>
{% endblock maincontent %}

useraccount/templates/changepassword.html
{% extends 'base_site.html' %}
{% block maincontent %}

<form method="POST" enctype="multipart/form-data"> 
     {% csrf_token %}
  
    {{ form.non_field_errors }}
    {% for user in userprofile%}
     <div class="form-group my-2">
        <label> {{user.label_tag}}</label>
        {{ user }}
        <span class="text text-danger">{{ user.errors }}</span>
    
   
    {% endfor %}


    {% for field in form%}
     <div class="form-group my-2">
        <label> {{field.label_tag}}</label>
        {{ field }}
        <span class="text text-danger">{{ field.errors }}</span>
    
   
    {% endfor %}
</form>
    <input type="submit" class="btn btn-primary" value="Submit">
</form>


{% endblock maincontent %}

useraccount/templates/login.html
{% extends 'base_site.html' %}
{% block maincontent %}
  
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    <!-- {{form.as_p}}  -->
     <!-- # this is from the dictionary key in views.py for the required form -->
    {{ form.non_field_errors }}
{% for field in form%}
 <div class="form-group my-2">
    <label> {{field.label_tag}}</label>
    {{ field }}
    <span class="text text-danger">{{ field.errors }}</span>

</div>
{% endfor %}

    <input type="submit" name="Submit" class="btn btn-primary" value="Submit" id="">
</form>
{% endblock maincontent %}

useraccount/templates/profile.html
{% extends 'base_site.html' %} {% block maincontent %}
<style>
  body {
    margin-top: 20px;
    color: #1a202c;
    text-align: left;
    background-color: #e2e8f0;
  }
  .main-body {
    padding: 15px;
  }
  .card {
    box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);
  }

  .card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0, 0, 0, 0.125);
    border-radius: 0.25rem;
  }

  .card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
  }

  .gutters-sm {
    margin-right: -8px;
    margin-left: -8px;
  }

  .gutters-sm > .col,
  .gutters-sm > [class*="col-"] {
    padding-right: 8px;
    padding-left: 8px;
  }
  .mb-3,
  .my-3 {
    margin-bottom: 1rem !important;
  }

  .bg-gray-300 {
    background-color: #e2e8f0;
  }
  .h-100 {
    height: 100% !important;
  }
  .shadow-none {
    box-shadow: none !important;
  }
</style>

<div class="container">
  <div class="main-body">
    <!-- /Breadcrumb -->
    {%include 'message.html'%}
    <div class="row gutters-sm">
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="d-flex flex-column align-items-center text-center">
              {% if user.image %}
              <img
                src="{{ user.image.url }}"
                alt="{{users.username}}"
                class="rounded-circle"
                width="150"
              />
              {% else %} 
              {% load static %}
              <img
                src="{% static 'images/user.png' %}"
                alt="Profile Picture"
                class="rounded-circle"
                width="150"
              />
              {% endif %}
              <div class="mt-3">
                <h4>{{users.first_name}} {{ users.last_name}}</h4>
                <p class="text-secondary mb-1">@{{users.username}}</p>
                <p class="text-muted font-size-sm">{{users.email}}</p>

                <a href="{% url 'booking:booking_history' user.id%}"
                  ><button class="btn btn-primary">Hotel Bookings</button></a
                >
                <a href="{% url 'booking:flight_booking_history' user.id%}">
                  <button class="btn btn-secondary">Flight Bookings</button>
                </a>
                <a class="mt-2" href="{% url 'user:change_password' %}"
                  ><button class="btn btn-link">Change Password</button></a
                >
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="card mb-3">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Full Name</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                {{users.first_name}} {{users.last_name}}
              </div>
            </div>
            <hr />
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">UserName</h6>
              </div>
              <div class="col-sm-9 text-secondary">{{users.username}}</div>
            </div>
            <hr />
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Email</h6>
              </div>
              <div class="col-sm-9 text-secondary">{{users.email}}</div>
            </div>
            <hr />
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Phone</h6>
              </div>
              <div class="col-sm-9 text-secondary">{{users.phone}}</div>
            </div>
            <hr />

            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Address</h6>
              </div>
              <div class="col-sm-9 text-secondary">{{users.address}}</div>
            </div>
            <hr />
            <div class="row">
              <div class="col-sm-12">
                <a
                  class="btn btn-info"
                  href="{% url 'user:edit_profile' user.id%}"
                  >Edit Profile</a
                >
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock maincontent %}

useraccount/templates/profile_edit.html
{% extends 'base.html' %}
{% block content %}

<form method="POST" enctype="multipart/form-data"> 
     {% csrf_token %}
  
    {{ form.non_field_errors }}
    {% for user in userprofile%}
     <div class="form-group my-2">
        <label> {{user.label_tag}}</label>
        {{ user }}
        <span class="text text-danger">{{ user.errors }}</span>
    
   
    {% endfor %}


    {% for field in form%}
     <div class="form-group my-2">
        <label> {{field.label_tag}}</label>
        {{ field }}
        <span class="text text-danger">{{ field.errors }}</span>
    
   
    {% endfor %}
</form>
    <input type="submit" class="btn btn-primary" value="Submit">
</form>


{% endblock content %}

useraccount/templates/register.html
{% extends 'base_site.html' %}
{% block maincontent %}
  
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
  
     <!-- # this is from the dictionary key in views.py for the required form -->
    {{ form.non_field_errors }}
{% for field in form%}
 <div class="form-group my-2">
    <label> {{field.label_tag}}</label>
    {{ field }}
    <span class="text text-danger">{{ field.errors }}</span>

</div>
{% endfor %}

    <input type="submit" name="Submit" class="btn btn-primary" value="Submit" id="">
</form>
<a href="{% url 'user:login' %}">Login</a>
{% endblock maincontent %}