bookings/urls.py
from django.urls import path
# from .views import CreateBooking
from .views import createBooking,bookingHistory,cancelBooking,book_flight,flightbookingHistory,cancelFlightBooking

app_name = "booking"

urlpatterns = [
    # path("booking/<int:hotelid>", CreateBooking.as_view(), name="create_booking"),
    path("booking/<int:hotelid>", createBooking, name="create_booking"),
    path("booking-history/<int:userid>", bookingHistory, name="booking_history"),
    path("cancel-booking/", cancelBooking, name="cancel_booking"),
     path("book-flight/", book_flight, name="book_flight"),
     path("flight-booking-history/<int:userid>", flightbookingHistory, name="flight_booking_history"),
    path("cancel-flight-booking/", cancelFlightBooking, name="cancel_flight_booking"),

    ]

hotel/urls.py
from django.urls import path
from hotel.views import homepage_view, hotel_detail_view, search_view,sort_hotel,termsandconditions

app_name = "hotel"

urlpatterns = [
    path("", homepage_view, name="homepage"),
    path("search/", search_view, name="searchhotel"),
    path("hotel/<int:hotelid>/", hotel_detail_view, name="hotel_detail"),
    path("terms-and-condition",termsandconditions,name="terms"),
    path('sort-hotels/', sort_hotel, name='sort_hotel')
]

travelsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("site/admin/", admin.site.urls),
    path("", include("hotel.urls", namespace="hotel")),
    path("", include("flight.urls", namespace="flight")),
    path("", include("payment.urls", namespace="payment")),

    path("", include("bookings.urls", namespace="booking")),
    path("", include("useraccount.urls", namespace="user")),
    path("", include("client.urls", namespace="client")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Travel Admin"
admin.site.site_title = " Travel Portal"
admin.site.index_title = "Welcome to Travel Admin Portal"

bookings/models.py
from django.db import models
from useraccount.models import User
from hotel.models import Hotel
from flight.models import Flight
from django.db.models.functions import Now

# Create your models here.
class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

BOOL_CHOICES = ((True, 'Booked'), (False, 'Cancelled'))

class Booking(TimeStamp):
    check_in_date=models.DateField()
    check_out_date=models.DateField()
    amount=models.FloatField()
    user=models.ForeignKey(User ,
        on_delete=models.CASCADE)
    
    hotel=models.ForeignKey(Hotel,on_delete=models.CASCADE)
    status = models.BooleanField(choices=BOOL_CHOICES,default=True)
    transaction_id = models.CharField(max_length=500, null=True, blank=True)


    def __str__(self):
        return self.hotel.hotel_name
    
    def duration(self):
        return ((self.check_out_date - self.check_in_date).days)+1
    

class FlightBooking(TimeStamp):
    amount=models.FloatField(null=True, blank=True)
    user=models.ForeignKey(User ,
        on_delete=models.CASCADE)
    flight=models.ForeignKey(Flight,on_delete=models.CASCADE)
    status = models.BooleanField(choices=BOOL_CHOICES,default=True)
    transaction_id = models.CharField(max_length=500,null=True, blank=True)

hotel/models.py
from django.db import models
from useraccount.models import User
from django.core.validators import FileExtensionValidator

# Create your models here.
class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
class AmnitiesOptions(models.TextChoices):
    ROOMSERVICE = "Room Service", "Room Service"
    PARKING = "Parking", "Parking"
    WIFI = "Wifi", "Wifi"
    SWIMMINGPOOL = "Swimming Pool", "Swimming Pool"
    GYM = "Gym", "Gym"
    SPA = "Spa", "Spa"
    GARDEN = "Garden", "Garden"
    CHILDRENSPLAYAREA = "Children's Play Area", "Children's Play Area"
    BAR = "Bar", "Bar"
   

    

class Amnities(TimeStamp):
    amenity=models.CharField(max_length=255,choices=AmnitiesOptions.choices)

    def __str__(self):
        return self.amenity
    



class Hotel(TimeStamp):
    hotel_name = models.CharField(max_length=255)
    hotel_description=models.TextField()
    amenities=models.ManyToManyField(Amnities)
    email = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    banner_image=models.ImageField(upload_to="hotelimages")
    price_per_day=models.FloatField()
    added_by=models.ForeignKey(User,on_delete=models.CASCADE)
    class Meta:
        ordering = ['-id']
    def __str__(self):
        return self.hotel_name
    def get_amneties(self):
        amenities_list=[]
        for amenity in self.amenities.all():
            amenities_list.append({'id':amenity.id,'amenity':amenity.amenity})
        return amenities_list

class Image(models.Model):
    image = models.ImageField(upload_to="hotelimages", blank=True, null=True )
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE,related_name="hotel_image")
    def __str__(self):
        return self.hotel.hotel_name



class Phone(models.Model):
    landline = models.CharField(max_length=255)
    mobile = models.CharField(max_length=255)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE,related_name="hotel_phone")
    def __str__(self):
        return self.hotel.hotel_name

bookings/forms.py
from django import forms
from .models import Booking
from django.core.exceptions import ValidationError
from django.utils import timezone
from datetime import date


class BookingForm(forms.ModelForm):
    class Meta:
        model=Booking
        # fields="__all__"
        fields=(
           "check_in_date",
           "check_out_date",
           
        )
        widgets = {
            
            'check_in_date':forms.DateInput(attrs={'type':'date'}),
            'check_out_date':forms.DateInput(attrs={'type':'date'})
        }
    def clean(self):
        cleaned_data = super().clean()
        check_in_date = cleaned_data.get('check_in_date')
        check_out_date = cleaned_data.get('check_out_date')

        if not check_in_date or not check_out_date:
            # Don't proceed with further validation if either date is missing
            return cleaned_data

        today = date.today()
        if check_in_date < today:
            raise ValidationError("Check-in date cannot be in the past.")
        if check_out_date < today:
            raise ValidationError("Check-out date cannot be in the past.")
        if check_out_date <= check_in_date:
            raise ValidationError("Check-out date cannot be earlier than check-in date.")

        return cleaned_data
    
    # def clean_check_in_date(self):
    #     check_in_date = self.cleaned_data.get('check_in_date')
    #     check_out_date = self.cleaned_data.get('check_out_date')
    #     today = date.today()
    #     if check_in_date < today:
    #         raise ValidationError('Check-in date cannot be a past date.')
    #     print(check_in_date)
    #     print(check_out_date)
    #     if check_out_date < timezone.now().date():
    #         raise ValidationError('Check-out date cannot be a past date.')
      
    #     return check_in_date,check_out_date

    # def clean_check_out_date(self):
    #     check_in_date = self.cleaned_data.get('check_in_date')
    #     check_out_date = self.cleaned_data.get('check_out_date')
    #     print(check_in_date)
    #     print(check_out_date)
    #     if check_out_date < timezone.now().date():
    #         raise ValidationError('Check-out date cannot be a past date.')
    #     if check_out_date <= check_in_date:
    #         raise ValidationError('Check-out date must be after check-in date.')
    #     return check_out_date
    
    
   

    

bookings/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import BookingForm
from payment.models import UserPayment
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from hotel.models import Hotel
from .models import Booking
import stripe
from datetime import date
from django.conf import settings
from flight.models import Flight
from bookings.models import FlightBooking
import math 



# Create your views here.


@login_required
def createBooking(request, hotelid):
    stripe.api_key = settings.STRIPE_SECRET_KEY
    hotel = get_object_or_404(Hotel, id=hotelid)
    if request.method == "POST":
        booking_form = BookingForm(request.POST)
        if booking_form.is_valid():
            booking = booking_form.save(commit=False)
            booking.hotel_id = hotel.id
            booking.user_id = request.user.id
            booking.amount = booking.duration() * hotel.price_per_day
            fee=booking.amount * 0.25
            print( hotel.added_by.id)
            checkout_session=stripe.checkout.Session.create(
                mode="payment",
                 line_items=[
                    {
                        "price_data": {
                            "currency": "usd",
                            "unit_amount": int(booking.amount) * 100,
                            "product_data": {
                                "name": "Hotel booking",
                            },
                        },
                        "quantity": 1,
                    },
                ],
                payment_intent_data={
                    "application_fee_amount":  int(fee)*100,
                     "transfer_data": {"destination": hotel.added_by.stripe_customer_id},
                        },
                        customer_creation="always",
                success_url=settings.REDIRECT_DOMAIN
                + "/payment_successful?session_id={CHECKOUT_SESSION_ID}",
                cancel_url=settings.REDIRECT_DOMAIN + "/payment_cancelled",
                )
            
            booking.transaction_id = checkout_session.id
            booking.status = False
            booking.save()
            return redirect(checkout_session.url, code=303)
    else:
        booking_form = BookingForm()
    return render(request, "make_booking.html", {"form": booking_form, "hotel": hotel})


@login_required
def bookingHistory(request, userid):
    today = date.today()
    bookinghistory = Booking.objects.filter(user_id=userid, check_in_date__lt=today,status=True)
    upcomingbookings = Booking.objects.filter(user_id=userid, check_in_date__gte=today, status=True)
    return render(request, "booking_history.html", {"booking": bookinghistory,"upcomingbookings":upcomingbookings})


@login_required
def cancelBooking(request):
    bookingid=request.POST.get("bookingid")
    booking=Booking.objects.get(id=bookingid)
    payment=UserPayment.objects.get(stripe_checkout_id=booking.transaction_id)
    booking.status=False
    final_amount=booking.amount-booking.amount*0.8
    booking.amount=final_amount
    payment.amount=final_amount
    booking.save()
    payment.save()
    return redirect(reverse("booking:booking_history", args=(request.user.id,)))


@login_required
def book_flight(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY

    if request.method == 'POST':
        flight_id = int(request.POST.get('flightid'))
        predicted_price = float(request.POST.get('price'))
        flight=Flight.objects.get(id=flight_id)
      
        checkout_session=stripe.checkout.Session.create(
            mode="payment",
             line_items=[
                {
                    "price_data": {
                        "currency": "usd",
                        "unit_amount": math.floor(predicted_price)*100,
                        "product_data": {
                            "name": "Flight booking",
                        },
                    },
                    "quantity": 1,
                },
            ],
            customer_creation="always",
            success_url=settings.REDIRECT_DOMAIN
            + "/payment_successful_flight?session_id={CHECKOUT_SESSION_ID}",
            cancel_url=settings.REDIRECT_DOMAIN + "/payment_cancelled",
            )
        book_flight=FlightBooking.objects.create(flight=flight, user_id=request.user.id, amount=predicted_price, status=False,transaction_id=checkout_session.id)
        book_flight.save()
        return redirect(checkout_session.url, code=303)
            
    return render(request, 'book.html')
    


@login_required
def flightbookingHistory(request, userid):
    today = date.today()
    bookinghistory = FlightBooking.objects.filter(user_id=userid,status=True)
    upcomingbookings = FlightBooking.objects.filter(user_id=userid,status=True)
    # upcomingbookings = FlightBooking.objects.filter(user_id=userid, check_in_date__gte=today, status=True)
    return render(request, "flight_bookings.html", {"booking": bookinghistory,"upcomingbookings":upcomingbookings})

@login_required
def cancelFlightBooking(request):
    bookingid=request.POST.get("bookingid")
    booking=FlightBooking.objects.get(id=bookingid)
    payment=UserPayment.objects.get(stripe_checkout_id=booking.transaction_id)
    booking.status=False
    final_amount=booking.amount-booking.amount*0.8
    booking.amount=final_amount
    payment.amount=final_amount
    booking.save()
    payment.save()
    return redirect(reverse("booking:booking_history", args=(request.user.id,)))

bookings/templates/booking_history.html
{% extends 'base_site.html' %} {% block maincontent %}

<table class="table">
  <caption>
    Upcoming Bookings
  </caption>
  <thead>
    <tr>
      <th scope="col">S.N</th>
      <th scope="col">Check In Date</th>
      <th scope="col">Check Out Date</th>
      <th scope="col">Amount</th>
      <th scope="col">Hotel</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for upcomingbooking in upcomingbookings %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{upcomingbooking.check_in_date}}</td>
      <td>{{upcomingbooking.check_out_date}}</td>
      <td>${{upcomingbooking.amount}}</td>
      <td>{{upcomingbooking.hotel.hotel_name}}</td>
      <td>
        <button
          data-bookingid="{{upcomingbooking.id}}"
          class="btn btn-danger"
          data-bs-toggle="modal"
          data-bs-target="#exampleModal"
        >
          Cancel
        </button>
      </td>
    </tr>

    {% endfor %}
  </tbody>
</table>
<table class="table">
  <caption>
    Bookings History
  </caption>
  <thead>
    <tr>
      <th scope="col">S.N</th>
      <th scope="col">Check In Date</th>
      <th scope="col">Check Out Date</th>
      <th scope="col">Amount</th>
      <th scope="col">Hotel</th>
    </tr>
  </thead>
  <tbody>
    {% for bookinghistory in booking %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{bookinghistory.check_in_date}}</td>
      <td>{{bookinghistory.check_out_date}}</td>
      <td>${{bookinghistory.amount}}</td>
      <td>{{bookinghistory.hotel.hotel_name}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<div
  class="modal fade"
  id="exampleModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Cancel Booking</h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        Are You Sure You Want to Cancel Booking?
        <form
          id="deleteform"
          method="post"
          action="{% url 'booking:cancel_booking'%}"
        >
          {% csrf_token %}
          <input type="hidden" name="bookingid" id="_bookingid" />
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          No
        </button>
        <button id="deletebutton" type="submit" class="btn btn-danger">
          Yes
        </button>
      </div>
    </div>
  </div>
</div>

{% endblock maincontent %} {% block script%} {{ block.super }}
<script type="text/javascript">
  $(document).ready(function () {
    let modal = document.getElementById("exampleModal");
    modal.addEventListener("show.bs.modal", function (evt) {
      let btn = evt.relatedTarget;
      let bookingid = btn.dataset.bookingid;
      $("#_bookingid").val(bookingid);
    });
    $("#deletebutton").click(function () {
      $("#deleteform").submit();
    });
  });
</script>
{% endblock script %}

bookings/templates/flight_bookings.html
{% extends 'base_site.html' %} {% block maincontent %}

<table class="table">
  <caption>
    Upcoming Bookings
  </caption>
  <thead>
    <tr>
      <th scope="col">S.N</th>
      <th scope="col">Departure Date</th>
      <th scope="col">Arrival Date</th>
      <th scope="col">Amount</th>
      <th scope="col">Airline</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for upcomingbooking in upcomingbookings %} 
    

    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{upcomingbooking.flight.departure_date}}</td>
      <td>{{upcomingbooking.flight.arrival_date}}</td>
      <td>${{upcomingbooking.amount}}</td>
      <td>{{upcomingbooking.flight.airline}}</td>
      <td>
        <button
          data-bookingid="{{upcomingbooking.id}}"
          class="btn btn-danger"
          data-bs-toggle="modal"
          data-bs-target="#exampleModal"
        >
          Cancel
        </button>
      </td>
    </tr>
 
     {% endfor %}
  </tbody>
</table>
<table class="table">
  <caption>
    Bookings History
  </caption>
  <thead>
    <tr>
      <th scope="col">S.N</th>
      <th scope="col">Departure Date</th>
      <th scope="col">Arrival Date</th>
      <th scope="col">Amount</th>
      <th scope="col">Airline</th>
    </tr>
  </thead>
  <tbody>
    {% for bookinghistory in booking %} 
   
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{bookinghistory.flight.departure_date}}</td>
      <td>{{bookinghistory.flight.arrival_date}}</td>
      <td>${{bookinghistory.amount}}</td>
      <td>{{bookinghistory.flight.airline}}</td>
    </tr>
  
    {% endfor %}
  </tbody>
</table>
<div
  class="modal fade"
  id="exampleModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Cancel Booking</h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        Are You Sure You Want to Cancel Booking?
        <form
          id="deleteform"
          method="post"
          action="{% url 'booking:cancel_flight_booking'%}"
        >
          {% csrf_token %}
          <input type="hidden" name="bookingid" id="_bookingid" />
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          No
        </button>
        <button id="deletebutton" type="submit" class="btn btn-danger">
          Yes
        </button>
      </div>
    </div>
  </div>
</div>

{% endblock maincontent %} {% block script%} {{ block.super }}
<script type="text/javascript">
  $(document).ready(function () {
    let modal = document.getElementById("exampleModal");
    modal.addEventListener("show.bs.modal", function (evt) {
      let btn = evt.relatedTarget;
      let bookingid = btn.dataset.bookingid;
      $("#_bookingid").val(bookingid);
    });
    $("#deletebutton").click(function () {
      $("#deleteform").submit();
    });
  });
</script>
{% endblock script %}

bookings/templates/make_booking.html
{% extends 'base_site.html' %}

{% block maincontent %} 
 <style type="text/css">
         .li{
            list-style-type: none !important;
         }
        
      </style>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- {{form.as_p}}  -->
     <!-- # this is from the dictionary key in views.py for the required form -->
{% for field in form%}
 <div class="form-group my-2">
    <label> {{field.label_tag}}</label>
    {{ field }}
    <span class="text text-danger" >{{ field.errors }}</span>

</div>
{% endfor %}
    <span class="text text-danger">{{ form.non_field_errors }}</span>


<input type="" value="{{request.user}}" hidden>
<input type=""  value="{{hotel.hotel_name}}" hidden></br>
<p>Price Per Day: Rs{{hotel.price_per_day}}</p>
<input type="" id="id_price_per_day" value="{{hotel.price_per_day}}" hidden>
    <input type="button" name="price" onclick="datediff()"  class="btn btn-primary" value="Show Total Price" id="">
    <input type="submit" name="Submit" onclick="datediff()"  class="btn btn-primary" value="Submit" id="">
</form>
Total Price: $<p id="total_price">0.00</p>
<script>
    function datediff(){
    var d1=new Date(document.getElementById("id_check_in_date").value);
    var d2=new Date(document.getElementById("id_check_out_date").value);
    var price_per_day= document.getElementById("id_price_per_day").value;
    var diff = d2.getTime() - d1.getTime();  
    var present=new Date(Date.now());
    console.log(present)
    // if(d1<present && d2<present){
    //     alert('hi');
    // }
   
      if(d1<d2){
               var daydiff = (diff / (1000 * 60 * 60 * 24))+1;   
    document.getElementById("total_price").innerHTML=daydiff*price_per_day
      }
    // console.log(d1);
    // console.log(d2);
    // console.log(price_per_day)
    // console.log(daydiff)

    
}
   
</script>


   

{% endblock maincontent %}