bookings/urls.py
from django.urls import path
# from .views import CreateBooking
from .views import createBooking,bookingHistory,cancelBooking,book_flight,flightbookingHistory,cancelFlightBooking

app_name = "booking"

urlpatterns = [
    # path("booking/<int:hotelid>", CreateBooking.as_view(), name="create_booking"),
    path("booking/<int:hotelid>", createBooking, name="create_booking"),
    path("booking-history/<int:userid>", bookingHistory, name="booking_history"),
    path("cancel-booking/", cancelBooking, name="cancel_booking"),
     path("book-flight/", book_flight, name="book_flight"),
     path("flight-booking-history/<int:userid>", flightbookingHistory, name="flight_booking_history"),
    path("cancel-flight-booking/", cancelFlightBooking, name="cancel_flight_booking"),

    ]

client/urls.py
from django.urls import path
from .views import clientdashboard, add_hotel, add_phone, add_images,list_hotel,edit_hotel,delete_hotel,list_image,list_phone,delete_image,delete_phone,list_bookings,export_bookings,export_hotels,list_payments,export_payments
app_name = "client"
urlpatterns = [
    path("client-dashboard/", clientdashboard, name="clientdashboard"),
    path("addhotel/", add_hotel, name="add_hotel"),
    path("listhotel", list_hotel, name="list_hotel"),
    path("edithotel/<int:hotelid>/", edit_hotel, name="edit_hotel"),
    path("deletehotel/", delete_hotel, name="delete_hotel"),
    path("addphone/<int:hotelid>/", add_phone, name="add_phone"),
    path("listphone/", list_phone, name="list_phone"),
    path("addimages/<int:hotelid>/", add_images, name="add_image"),
    path("listimages/", list_image, name="list_image"),
    path("deleteimage/", delete_image, name="delete_image"),
    path("deletephone/", delete_phone, name="delete_phone"),
    path("listbookings/", list_bookings, name="list_bookings"),
    path("listpayments/", list_payments, name="list_payments"),
    path("exportbookings/", export_bookings, name="export_bookings"),
    path("exporthotels/", export_hotels, name="export_hotels"),
    path("exportpayments/", export_payments, name="export_payments"),
    

]

hotel/urls.py
from django.urls import path
from hotel.views import homepage_view, hotel_detail_view, search_view,sort_hotel,termsandconditions

app_name = "hotel"

urlpatterns = [
    path("", homepage_view, name="homepage"),
    path("search/", search_view, name="searchhotel"),
    path("hotel/<int:hotelid>/", hotel_detail_view, name="hotel_detail"),
    path("terms-and-condition",termsandconditions,name="terms"),
    path('sort-hotels/', sort_hotel, name='sort_hotel')
]

payment/urls.py
from django.urls import path
from . import views

app_name = "payment"

urlpatterns = [
    path("payment_successful", views.payment_successful, name="payment_successful"),
    path("payment_successful_flight", views.payment_successful_flight, name="payment_successful_flight"),
    path("payment_cancelled", views.payment_cancelled, name="payment_cancelled"),
    # path('stripe_webhook', views.stripe_webhook, name='stripe_webhook'),
]

useraccount/urls.py
from django.urls import path
from useraccount.views import UserLoginView, SignupView, user_profile, user_profile_edit,make_client,makeclientpage,password_change
from django.contrib.auth.views import LogoutView

app_name = "user"
urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", SignupView.as_view(), name="register"),
    path("profile/<user>/userid=<int:id>/", user_profile, name="userprofile"),
    path("profile-edit/<int:id>", user_profile_edit, name="edit_profile"),
    path(r'^password/$', password_change, name='change_password'),
    # path("password-change/<int:id>", password_change, name="change_password"),
    path("makeclient/", make_client, name="make_client"),
    path("becomeclient/", makeclientpage, name="make_client_page"),
]

bookings/models.py
from django.db import models
from useraccount.models import User
from hotel.models import Hotel
from flight.models import Flight
from django.db.models.functions import Now

# Create your models here.
class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

BOOL_CHOICES = ((True, 'Booked'), (False, 'Cancelled'))

class Booking(TimeStamp):
    check_in_date=models.DateField()
    check_out_date=models.DateField()
    amount=models.FloatField()
    user=models.ForeignKey(User ,
        on_delete=models.CASCADE)
    
    hotel=models.ForeignKey(Hotel,on_delete=models.CASCADE)
    status = models.BooleanField(choices=BOOL_CHOICES,default=True)
    transaction_id = models.CharField(max_length=500, null=True, blank=True)


    def __str__(self):
        return self.hotel.hotel_name
    
    def duration(self):
        return ((self.check_out_date - self.check_in_date).days)+1
    

class FlightBooking(TimeStamp):
    amount=models.FloatField(null=True, blank=True)
    user=models.ForeignKey(User ,
        on_delete=models.CASCADE)
    flight=models.ForeignKey(Flight,on_delete=models.CASCADE)
    status = models.BooleanField(choices=BOOL_CHOICES,default=True)
    transaction_id = models.CharField(max_length=500,null=True, blank=True)

client/models.py
from django.db import models

# Create your models here.

bookings/forms.py
from django import forms
from .models import Booking
from django.core.exceptions import ValidationError
from django.utils import timezone
from datetime import date


class BookingForm(forms.ModelForm):
    class Meta:
        model=Booking
        # fields="__all__"
        fields=(
           "check_in_date",
           "check_out_date",
           
        )
        widgets = {
            
            'check_in_date':forms.DateInput(attrs={'type':'date'}),
            'check_out_date':forms.DateInput(attrs={'type':'date'})
        }
    def clean(self):
        cleaned_data = super().clean()
        check_in_date = cleaned_data.get('check_in_date')
        check_out_date = cleaned_data.get('check_out_date')

        if not check_in_date or not check_out_date:
            # Don't proceed with further validation if either date is missing
            return cleaned_data

        today = date.today()
        if check_in_date < today:
            raise ValidationError("Check-in date cannot be in the past.")
        if check_out_date < today:
            raise ValidationError("Check-out date cannot be in the past.")
        if check_out_date <= check_in_date:
            raise ValidationError("Check-out date cannot be earlier than check-in date.")

        return cleaned_data
    
    # def clean_check_in_date(self):
    #     check_in_date = self.cleaned_data.get('check_in_date')
    #     check_out_date = self.cleaned_data.get('check_out_date')
    #     today = date.today()
    #     if check_in_date < today:
    #         raise ValidationError('Check-in date cannot be a past date.')
    #     print(check_in_date)
    #     print(check_out_date)
    #     if check_out_date < timezone.now().date():
    #         raise ValidationError('Check-out date cannot be a past date.')
      
    #     return check_in_date,check_out_date

    # def clean_check_out_date(self):
    #     check_in_date = self.cleaned_data.get('check_in_date')
    #     check_out_date = self.cleaned_data.get('check_out_date')
    #     print(check_in_date)
    #     print(check_out_date)
    #     if check_out_date < timezone.now().date():
    #         raise ValidationError('Check-out date cannot be a past date.')
    #     if check_out_date <= check_in_date:
    #         raise ValidationError('Check-out date must be after check-in date.')
    #     return check_out_date
    
    
   

    

client/forms.py
from django import forms
from hotel.models import Hotel, Phone, Image
from django.core.exceptions import ValidationError


class HotelCreationForm(forms.ModelForm):
    class Meta:
        model = Hotel
        exclude = ("added_by",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

    def clean_price_per_day(self):
        price_per_day = self.cleaned_data.get("price_per_day")
        print(price_per_day)
        if price_per_day <= 0:
            raise forms.ValidationError("Price can not be less than zero.")
        return price_per_day


class PhoneForm(forms.ModelForm):
    class Meta:
        model = Phone
        exclude = ("hotel",)


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"



# ALLOWED_FILE_FORMATS = ['jpeg', 'jpg', 'png', 'gif']

class ImageForm(forms.ModelForm):
  
    class Meta:
        model = Image
        exclude = ("hotel",)
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
  
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
    # def clean_image(self):
    #     image = self.files.getlist('image')
    #     if image:
    #         file_extension = image.name.split('.')[-1].lower()
    #         if file_extension not in ALLOWED_FILE_FORMATS:
    #             raise ValidationError(f"Unsupported file format. Only {', '.join(ALLOWED_FILE_FORMATS)} are allowed.")
    #     return image
    

bookings/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import BookingForm
from payment.models import UserPayment
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from hotel.models import Hotel
from .models import Booking
import stripe
from datetime import date
from django.conf import settings
from flight.models import Flight
from bookings.models import FlightBooking
import math 



# Create your views here.


@login_required
def createBooking(request, hotelid):
    stripe.api_key = settings.STRIPE_SECRET_KEY
    hotel = get_object_or_404(Hotel, id=hotelid)
    if request.method == "POST":
        booking_form = BookingForm(request.POST)
        if booking_form.is_valid():
            booking = booking_form.save(commit=False)
            booking.hotel_id = hotel.id
            booking.user_id = request.user.id
            booking.amount = booking.duration() * hotel.price_per_day
            fee=booking.amount * 0.25
            print( hotel.added_by.id)
            checkout_session=stripe.checkout.Session.create(
                mode="payment",
                 line_items=[
                    {
                        "price_data": {
                            "currency": "usd",
                            "unit_amount": int(booking.amount) * 100,
                            "product_data": {
                                "name": "Hotel booking",
                            },
                        },
                        "quantity": 1,
                    },
                ],
                payment_intent_data={
                    "application_fee_amount":  int(fee)*100,
                     "transfer_data": {"destination": hotel.added_by.stripe_customer_id},
                        },
                        customer_creation="always",
                success_url=settings.REDIRECT_DOMAIN
                + "/payment_successful?session_id={CHECKOUT_SESSION_ID}",
                cancel_url=settings.REDIRECT_DOMAIN + "/payment_cancelled",
                )
            
            booking.transaction_id = checkout_session.id
            booking.status = False
            booking.save()
            return redirect(checkout_session.url, code=303)
    else:
        booking_form = BookingForm()
    return render(request, "make_booking.html", {"form": booking_form, "hotel": hotel})


@login_required
def bookingHistory(request, userid):
    today = date.today()
    bookinghistory = Booking.objects.filter(user_id=userid, check_in_date__lt=today,status=True)
    upcomingbookings = Booking.objects.filter(user_id=userid, check_in_date__gte=today, status=True)
    return render(request, "booking_history.html", {"booking": bookinghistory,"upcomingbookings":upcomingbookings})


@login_required
def cancelBooking(request):
    bookingid=request.POST.get("bookingid")
    booking=Booking.objects.get(id=bookingid)
    payment=UserPayment.objects.get(stripe_checkout_id=booking.transaction_id)
    booking.status=False
    final_amount=booking.amount-booking.amount*0.8
    booking.amount=final_amount
    payment.amount=final_amount
    booking.save()
    payment.save()
    return redirect(reverse("booking:booking_history", args=(request.user.id,)))


@login_required
def book_flight(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY

    if request.method == 'POST':
        flight_id = int(request.POST.get('flightid'))
        predicted_price = float(request.POST.get('price'))
        flight=Flight.objects.get(id=flight_id)
      
        checkout_session=stripe.checkout.Session.create(
            mode="payment",
             line_items=[
                {
                    "price_data": {
                        "currency": "usd",
                        "unit_amount": math.floor(predicted_price)*100,
                        "product_data": {
                            "name": "Flight booking",
                        },
                    },
                    "quantity": 1,
                },
            ],
            customer_creation="always",
            success_url=settings.REDIRECT_DOMAIN
            + "/payment_successful_flight?session_id={CHECKOUT_SESSION_ID}",
            cancel_url=settings.REDIRECT_DOMAIN + "/payment_cancelled",
            )
        book_flight=FlightBooking.objects.create(flight=flight, user_id=request.user.id, amount=predicted_price, status=False,transaction_id=checkout_session.id)
        book_flight.save()
        return redirect(checkout_session.url, code=303)
            
    return render(request, 'book.html')
    


@login_required
def flightbookingHistory(request, userid):
    today = date.today()
    bookinghistory = FlightBooking.objects.filter(user_id=userid,status=True)
    upcomingbookings = FlightBooking.objects.filter(user_id=userid,status=True)
    # upcomingbookings = FlightBooking.objects.filter(user_id=userid, check_in_date__gte=today, status=True)
    return render(request, "flight_bookings.html", {"booking": bookinghistory,"upcomingbookings":upcomingbookings})

@login_required
def cancelFlightBooking(request):
    bookingid=request.POST.get("bookingid")
    booking=FlightBooking.objects.get(id=bookingid)
    payment=UserPayment.objects.get(stripe_checkout_id=booking.transaction_id)
    booking.status=False
    final_amount=booking.amount-booking.amount*0.8
    booking.amount=final_amount
    payment.amount=final_amount
    booking.save()
    payment.save()
    return redirect(reverse("booking:booking_history", args=(request.user.id,)))

payment/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from bookings.forms import BookingForm
from payment.models import UserPayment
from useraccount.models import User
from bookings.models import Booking,FlightBooking
import stripe



# Create your views here.
## use Stripe dummy card: 4242 4242 4242 4242
def payment_successful(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY
    checkout_session_id = request.GET.get("session_id", None)

    session = stripe.checkout.Session.retrieve(checkout_session_id)
    print(session)
    customer = stripe.Customer.retrieve(session.customer)
    user_payment = UserPayment(
        app_user=request.user, stripe_checkout_id=checkout_session_id, payment_bool=True,amount=session.amount_subtotal/100
    )
    user=User.objects.filter(id=request.user.id)
    user.update(stripe_session=checkout_session_id)
    bookings=Booking.objects.filter(user_id=request.user.id,status=False,transaction_id=checkout_session_id)
    bookings.update(status=True)
    user_payment.save()
    # user.save()
    # print(customer)
    return render(request, "payment_successful.html", {"customer": customer})
def payment_successful_flight(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY
    checkout_session_id = request.GET.get("session_id", None)

    session = stripe.checkout.Session.retrieve(checkout_session_id)
    print(session)
    customer = stripe.Customer.retrieve(session.customer)
    user_payment = UserPayment(
        app_user=request.user, stripe_checkout_id=checkout_session_id, payment_bool=True,amount=session.amount_subtotal/100
    )
    user=User.objects.filter(id=request.user.id)
    user.update(stripe_session=checkout_session_id)
    flightbookings=FlightBooking.objects.filter(user_id=request.user.id,status=False,transaction_id=checkout_session_id)
    flightbookings.update(status=True)
    user_payment.save()
    return render(request, "payment_successful_flight.html", {"customer": customer})


def payment_cancelled(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY
    return render(request, "payment_cancelled.html")

client/templates/bookings.html
{% extends 'front.html' %} {% block content %}

<div class="container-fluid">
  <div class="row">
    {% include 'sidebar.html' %}
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      
      <div
      class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"
      >
      <h1 class="h6">Hotel Bokings</h1>
    </div>
    <a href="{% url 'client:export_bookings'%}" class="btn btn-primary">Export Bookings</a>
      <div class="card-body mt-2">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>S.N</th>
              <th>Hotel Name</th>
              <th>Check In Date</th>
              <th>Check Out Date</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {% for booking in bookings %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{booking.hotel.hotel_name }}</td>
              <td>{{booking.check_in_date}}</td>
              <td>{{booking.check_out_date}}</td>
              <td>
                {% if booking.status %}
                <span class="badge bg-success ">
                  Booked
                </span>
                {% elif not booking.status  %}
                <span class="badge bg-danger"> Cancelled</span>
               
                {% endif %}
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <!-- <div
          class="modal fade"
          id="exampleModal"
          tabindex="-1"
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
        >
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">
                  Modal title
                </h1>
                <button
                  type="button"
                  class="btn-close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                ></button>
              </div>
              <div class="modal-body">
                Are You Sure You Want to delete this booking?
                <form
                  id="deleteform"
                  method="post"
                  action="{% url 'client:delete_hotel' %}"
                >
                  {% csrf_token %}
                  <input type="text" name="bookingid" id="_bookingid" />
                </form>
              </div>
              <div class="modal-footer">
                <button
                  type="button"
                  class="btn btn-secondary"
                  data-bs-dismiss="modal"
                >
                  No
                </button>
                <button id="deletebutton" type="submit" class="btn btn-danger">
                  Yes
                </button>
              </div>
            </div>
          </div>
        </div>
      </div> -->
    </main>
  </div>
</div>

{% endblock %} {% block script%} {{ block.super }}
<!-- <script type="text/javascript">
  $(document).ready(function () {
    let modal = document.getElementById("exampleModal");
    modal.addEventListener("show.bs.modal", function (evt) {
      let btn = evt.relatedTarget;
      let hotelid = btn.dataset.hotelid;
      $("#_hotelid").val(hotelid);
    });
    $("#deletebutton").click(function () {
      $("#deleteform").submit();
    });
  });
</script> -->
{% endblock script %}

client/templates/dashboard.html
{% extends 'front.html' %} {% block content %}

<div class="container-fluid">
  <div class="row">
    {% include 'sidebar.html' %}

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"
      >
        <h1 class="h5">Dashboard</h1>
      </div>
     <div class="row">
          <div class="col-lg-3 col-6">
  <!-- small box -->
  <div class="bg-warning text-white ml-2 p-3 rounded">
    <div class="inner">
      <h3>{{hotelcount}}</h3>
      <p>Hotels</p>
    </div>
    <div class="icon">
      <i class="bi bi-list-ul"></i>
    </div>
    <a href="{% url 'client:list_hotel'%}" class="btn btn-outline-light btn-sm">More info <i class="bi bi-arrow-right"></i></a>
  </div>
  </div>
          <div class="col-lg-3 col-6">

  <div class="bg-info text-white ml-2 p-3 rounded">
    <div class="inner">
      <h3>{{bookingcount}}</h3>
      <p>Bookings</p>
    </div>
    <div class="icon">
      <i class="bi bi-calendar-check"></i>
    </div>
    <a href="{% url 'client:list_bookings'%}" class="btn btn-outline-light btn-sm">More info <i class="bi bi-arrow-right"></i></a>
  </div>
  </div>
  <div class="col-lg-3 col-6">

  <div class="bg-success text-white ml-2 p-3 rounded">
    <div class="inner">
      <h3>${{totalpayment}}</h3>
      <p>Total Payment</p>
    </div>
    <div class="icon">
      <i class="bi bi-currency-dollar"></i>
    </div>
    <a href="{% url 'client:list_payments'%}" class="btn btn-outline-light btn-sm">More info <i class="bi bi-arrow-right"></i></a>
  </div>
  </div>
</div>

    </main>
  </div>
</div>

{% endblock %}

client/templates/header.html
<header
  class="navbar navbar-dark sticky-top p-0"
  style="box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); background-color: #dedfe0"
>
  <a
    class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 ps-5"
    id="company_name"
    href="{% url 'hotel:homepage' %}"
    style="color: black"
    >Travel</a
  >
  <button
    class="navbar-toggler position-absolute d-md-none collapsed"
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#sidebarMenu"
    aria-controls="sidebarMenu"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-nav" style="background-color: #dedfe0">
    <div class="nav-item text-nowrap">
      <a
        class="nav-link px-3"
        href="{% url 'user:logout' %}"
        style="color: black"
        >Log out<i class="bi bi-box-arrow-right ps-2"></i
      ></a>
    </div>
  </div>
</header>

client/templates/hotel_list.html
{% extends 'front.html' %} {% block content %}

<div class="container-fluid">
  <div class="row">
    {% include 'sidebar.html' %}
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      {%include 'message.html'%}
      <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"
      >
        <h1 class="h6">Hotel List</h1>
      </div>
      <a href="{% url 'client:export_hotels'%}" class="btn btn-primary"
        >Export Hotel</a
      >

      <div class="card-body mt-2">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>S.N</th>
              <th>Hotel Name</th>
              <th>Email</th>
              <th>Banner Image</th>
              <th>Address</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for hotel in hotels %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>
                <a href="{% url 'client:edit_hotel' hotel.id%}"
                  >{{hotel.hotel_name}}</a
                >
              </td>
              <td>{{hotel.email}}</td>
              <td>
                <img
                  height="150px"
                  width="150px"
                  src="{{hotel.banner_image.url}}"
                />
              </td>
              <td>{{hotel.city}}</td>
              <td>
                <button class="btn btn-primary mt-2">
                  <a
                    href="{% url 'client:add_image' hotel.id %}"
                    class="text text-white"
                    >Add Images</a
                  ></button
                ><br /><button class="btn btn-primary mt-2">
                  <a
                    href="{% url 'client:add_phone' hotel.id %}"
                    class="text text-white"
                    >Add Phone</a
                  ></button
                ><br /><button
                  data-hotelid="{{hotel.id}}"
                  class="btn btn-danger"
                  data-bs-toggle="modal"
                  data-bs-target="#exampleModal"
                >
                  Delete
                </button>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <div
          class="modal fade"
          id="exampleModal"
          tabindex="-1"
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
        >
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">
                  Modal title
                </h1>
                <button
                  type="button"
                  class="btn-close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                ></button>
              </div>
              <div class="modal-body">
                Are You Sure You Want to delete this Hotel?
                <form
                  id="deleteform"
                  method="post"
                  action="{% url 'client:delete_hotel' %}"
                >
                  {% csrf_token %}
                  <input type="text" name="hotelid" id="_hotelid" />
                </form>
              </div>
              <div class="modal-footer">
                <button
                  type="button"
                  class="btn btn-secondary"
                  data-bs-dismiss="modal"
                >
                  No
                </button>
                <button id="deletebutton" type="submit" class="btn btn-danger">
                  Yes
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</div>

{% endblock %} {% block script%} {{ block.super }}
<script type="text/javascript">
  $(document).ready(function () {
    let modal = document.getElementById("exampleModal");
    modal.addEventListener("show.bs.modal", function (evt) {
      let btn = evt.relatedTarget;
      let hotelid = btn.dataset.hotelid;
      $("#_hotelid").val(hotelid);
    });
    $("#deletebutton").click(function () {
      $("#deleteform").submit();
    });
  });
</script>
{% endblock script %}

client/templates/payment.html
{% extends 'front.html' %} {% block content %}

<div class="container-fluid">
  <div class="row">
    {% include 'sidebar.html' %}
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      
      <div
      class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"
      >
      <h1 class="h6">Hotel Bokings</h1>
    </div>
    <a href="{% url 'client:export_payments'%}" class="btn btn-primary">Export Payments</a>
      <div class="card-body mt-2">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>S.N</th>
              <th>Amount</th>
              <th>Paid Date</th>
              <th>Updated Date</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {% for payment in payments %}
            <tr>
              <td>{{ forloop.counter }}</td>
                <td>{{payment.amount}}</td>
              <td>{{payment.created_at }}</td>
              <td>{{payment.modified_at}}</td>
             
              <td>
                {% if payment.payment_bool %}
                <span class="badge bg-success ">
                  Paid
                </span>
                {% elif not payment.payment_bool  %}
                <span class="badge bg-danger"> Cancelled</span>
               
                {% endif %}
            </tr>
            {% endfor %}
          </tbody>
        </table>
        
    </main>
  </div>
</div>

{% endblock %}
 {% block script%} 
 {{ block.super }}

{% endblock script %}

client/templates/sidebar.html
<nav
  id="sidebarMenu"
  class="col-md-3 col-lg-2 d-md-block bg-body-tertiary sidebar collapse"
>
  <div class="position-sticky pt-3 sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <a
          class="nav-link active"
          aria-current="page"
          href="{% url 'client:clientdashboard' %}"
          style="color: black"
        >
          <i class="bi bi-house-door-fill"></i>
          Dashboard
        </a>
      </li>
      <li class="nav-item">
        <a
          class="nav-link"
          href="{% url 'client:add_hotel'%}"
          style="color: black"
        >
          <i class="bi bi-plus-square-fill"></i>
          Add Hotel
        </a>
      </li>

      <li class="nav-item">
        <a
          class="nav-link"
          href="{% url 'client:list_hotel'%}"
          style="color: black"
        >
          <i class="bi bi-list-ul"></i>
          View Hotels
        </a>
      </li>
      <li class="nav-item">
        <a
          class="nav-link"
          href="{% url 'client:list_image'%}"
          style="color: black"
        >
          <i class="bi bi-list-ul"></i>
          View Images
        </a>
      </li>
      <li class="nav-item">
        <a
          class="nav-link"
          href="{% url 'client:list_phone'%}"
          style="color: black"
        >
          <i class="bi bi-list-ul"></i>
          View Phone Number
        </a>
      </li>
      <li class="nav-item">
        <a
          class="nav-link"
          href="{% url 'client:list_bookings'%}"
          style="color: black"
        >
          <i class="bi bi-calendar-check"></i>
          Bookings
        </a>
      </li>
      <li class="nav-item">
        <a
          class="nav-link"
          href="{% url 'client:list_payments'%}"
          style="color: black"
        >
          <i class="bi bi-currency-dollar"></i>
          Payments
        </a>
      </li>
    </ul>
  </div>
</nav>