client/urls.py
from django.urls import path
from .views import clientdashboard, add_hotel, add_phone, add_images,list_hotel,edit_hotel,delete_hotel,list_image,list_phone,delete_image,delete_phone,list_bookings,export_bookings,export_hotels,list_payments,export_payments
app_name = "client"
urlpatterns = [
    path("client-dashboard/", clientdashboard, name="clientdashboard"),
    path("addhotel/", add_hotel, name="add_hotel"),
    path("listhotel", list_hotel, name="list_hotel"),
    path("edithotel/<int:hotelid>/", edit_hotel, name="edit_hotel"),
    path("deletehotel/", delete_hotel, name="delete_hotel"),
    path("addphone/<int:hotelid>/", add_phone, name="add_phone"),
    path("listphone/", list_phone, name="list_phone"),
    path("addimages/<int:hotelid>/", add_images, name="add_image"),
    path("listimages/", list_image, name="list_image"),
    path("deleteimage/", delete_image, name="delete_image"),
    path("deletephone/", delete_phone, name="delete_phone"),
    path("listbookings/", list_bookings, name="list_bookings"),
    path("listpayments/", list_payments, name="list_payments"),
    path("exportbookings/", export_bookings, name="export_bookings"),
    path("exporthotels/", export_hotels, name="export_hotels"),
    path("exportpayments/", export_payments, name="export_payments"),
    

]

flight/urls.py
from django.urls import path
from flight.views import flightpredict
app_name = "flight"

urlpatterns = [
    path("flight", flightpredict, name="flight"),
  
]

hotel/urls.py
from django.urls import path
from hotel.views import homepage_view, hotel_detail_view, search_view,sort_hotel,termsandconditions

app_name = "hotel"

urlpatterns = [
    path("", homepage_view, name="homepage"),
    path("search/", search_view, name="searchhotel"),
    path("hotel/<int:hotelid>/", hotel_detail_view, name="hotel_detail"),
    path("terms-and-condition",termsandconditions,name="terms"),
    path('sort-hotels/', sort_hotel, name='sort_hotel')
]

travelsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("site/admin/", admin.site.urls),
    path("", include("hotel.urls", namespace="hotel")),
    path("", include("flight.urls", namespace="flight")),
    path("", include("payment.urls", namespace="payment")),

    path("", include("bookings.urls", namespace="booking")),
    path("", include("useraccount.urls", namespace="user")),
    path("", include("client.urls", namespace="client")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Travel Admin"
admin.site.site_title = " Travel Portal"
admin.site.index_title = "Welcome to Travel Admin Portal"

useraccount/urls.py
from django.urls import path
from useraccount.views import UserLoginView, SignupView, user_profile, user_profile_edit,make_client,makeclientpage,password_change
from django.contrib.auth.views import LogoutView

app_name = "user"
urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", SignupView.as_view(), name="register"),
    path("profile/<user>/userid=<int:id>/", user_profile, name="userprofile"),
    path("profile-edit/<int:id>", user_profile_edit, name="edit_profile"),
    path(r'^password/$', password_change, name='change_password'),
    # path("password-change/<int:id>", password_change, name="change_password"),
    path("makeclient/", make_client, name="make_client"),
    path("becomeclient/", makeclientpage, name="make_client_page"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% if title %}
       {{title}}
        {% else %} 
        Travel
        {% endif %}
      </title>
    <link rel="icon" href="{% static 'images/logo.png'%}" type="image/x-icon" />
    {% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/style.css'%}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css
"
    />
    {% endblock stylesheet %}
  </head>
  <body>
    <div class="container" >
      {% block content %} 
      {% endblock content %}
    </div>
    {% block script %}
    <script src="{% static 'js/jquery.min.js'%}"></script>
    <script src="{% static 'js/jqueryajax.min.js'%}"></script>
    <script src="{% static 'js/bs.min.js'%}"></script>
    {% endblock script %} 
    {% include 'footer.html'%}
  </body>
</html>

templates/base_site.html
{% extends 'base.html' %}
 {% block content %} 
 {% include 'navbar.html' %} 
 {% block maincontent %} 
 {% endblock maincontent %} 
 {% endblock content %}

templates/footer.html
<!-- Remove the container if you want to extend the Footer to full width. -->
<div class="container mt-5">
  <!-- Footer -->
  <footer
    class="text-center text-lg-start text-dark pt-2"
    style="background-color: hsl(0, 16%, 93%)"
  >
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <!-- <h6 class="text-uppercase fw-bold">Travel</h6>
            <hr
              class="mb-4 mt-0 d-inline-block mx-auto"
              style="width: 60px; background-color: #7c4dff; height: 2px"
            /> -->
            <br />
            {%load static%}
            <a href="{%url 'hotel:homepage'%}">
              <img src="{% static 'images/logo.png'%}" alt="" width="150px"
            /></a>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold">Services</h6>
            <hr
              class="mb-4 mt-0 d-inline-block mx-auto"
              style="width: 60px; background-color: #7c4dff; height: 2px"
            />
            <p>
              <a href="{% url 'flight:flight' %}" class="text-dark">Flights</a>
            </p>
            <p>
              <a href="{% url 'hotel:homepage' %}" class="text-dark">Hotel</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold">Useful links</h6>
            <hr
              class="mb-4 mt-0 d-inline-block mx-auto"
              style="width: 60px; background-color: #7c4dff; height: 2px"
            />

            <p>
              <a href="{% url 'user:make_client_page'  %}" class="text-dark"
                >Join Us</a
              >
            </p>
            <p>
              <a href="{% url 'hotel:terms' %}" class="text-dark">Terms and Conditions</a>
            </p>
            
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold">Contact</h6>
            <hr
              class="mb-4 mt-0 d-inline-block mx-auto"
              style="width: 60px; background-color: #7c4dff; height: 2px"
            />
            <p><i class="fas fa-home mr-3"></i> Kathmandu Nepal</p>
            <p><i class="fas fa-envelope mr-3"></i> travel@gmail.com</p>
            <p><i class="fas fa-phone mr-3"></i>9861386886</p>
            <p><i class="fas fa-phone mr-3"></i>9865412356</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  </footer>
  <!-- Footer -->
</div>
<!-- End of .container -->

templates/index.html
{% extends 'base.html' %}

{% block content %} 
{% include 'navbar.html' %}

<!-- <div class="row mt-2 pt-2">
    <div class="col-md-4">

        <label for="customRange1" class="form-label">Price</label>
        <input type="range" class="form-range" id="customRange1">
    </div>
</div> -->
<!-- 
<div class="row  mt-2 pt-2">
    {% for hotels in hotel %}

    <div class="col-md-4">
        <div class="card" style="width: 18rem;">
    {% if hotels.banner_image %}
            <img src="{{ hotels.banner_image.url }}" class="card-img-top" height="300px" alt="{{hotels.hotel_name}}">
            {% else %}
            {% load static %}
            <img src="{% static 'images/hoteldefault.png' %}" class="card-img-top" alt="{{hotels.hotel_name}}"></a>
    {% endif %}

            <div class="card-body">
                <h5 class="card-title">{{ hotels.hotel_name}}</h5>
                <p class="card-text">{{ hotels.hotel_description|truncatewords:50}}</p>
                <a href="{% url 'hotel:hotel_detail' hotels.id %}" class="btn btn-primary">See more</a>
            </div>
         </div>
    </div>
{% endfor %}

</div> -->


<div id="Hotel" class="tabcontent ml-2">
 <div class="row  mt-2 pt-2">
    {% for hotels in hotel %}

    <div class="col-md-4">
        <div class="card mb-2" style="width: 18rem;">
    {% if hotels.banner_image %}
            <img src="{{ hotels.banner_image.url }}" class="card-img-top" height="300px" alt="{{hotels.hotel_name}}">
            {% else %}
            {% load static %}
            <img src="{% static 'images/hoteldefault.png' %}" class="card-img-top" alt="{{hotels.hotel_name}}"></a>
    {% endif %}

            <div class="card-body ">
                <h5 class="card-title">{{ hotels.hotel_name}}</h5>
                <h6 class="card-title">{{ hotels.city}}</h6>
                
                <p class="card-text">Price Per Day:${{ hotels.price_per_day}}</p>

                <a href="{% url 'hotel:hotel_detail' hotels.id %}" class="btn btn-primary">See more</a>
            </div>
         </div>
    </div>
{% endfor %}

</div>
</div>
 
<center>
{% if hotel.has_previous %}

    <a href="?page={{hotel.previous_page_number}}">

      <button type="button" class="btn btn-primary btn-sm">Previous Page</button>

    </a>

{% endif%}

{% if hotel.has_next %}

    <a href="?page={{hotel.next_page_number}}">

      <button type="button" class="btn btn-secondary btn-sm">Next Page</button>

    </a>

{% endif%}
</center>

{% endblock content %}

templates/message.html
{% load static %}

<style>
  .alert {
    width: 50%;
  }
</style>

<!-- <script type="text/javascript">
  setTimeout(function () {
    $(".alert").alert("close");
  }, 1000);
</script> -->
<script type="text/javascript">
  setTimeout(function () {
    $(".alert").fadeOut("slow");
  }, 15000); // Auto-close after 15 seconds

  $(".alert").on("close.bs.alert", function () {
    // User closed the alert
    $(this).fadeOut("fast");
  });
</script>

{% if messages %} 
{% for message in messages %}
 {% if message.tags == 'success'%}

 <div class="alert alert-{{ message.tags }} fade show d-flex justify-content-between align-items-center" role="alert" id="alert">
  <strong>{{ message }}</strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

</div>
{% endif %} {% if message.tags == 'error' %}
<div class="alert alert-danger fade show d-flex justify-content-between align-items-center" role="alert" id="alert">
  <strong>{{ message }}</strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

{% endif %} {% endfor %} {% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'hotel:homepage' %}"
            >Hotels</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'flight:flight' %}"
            >Flights</a
          >
        </li>
        {% if request.user.is_authenticated and request.user.is_client %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'client:clientdashboard' %}"
            >Client Dashboard</a
          >
        </li>
        {% endif %}
        
        
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a
            class="nav-link"
            href="{% url 'user:userprofile' user.username user.id %}"
            >My Profile</a
          >
        </li>
       
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:logout' %}">Log Out</a>
        </li>

        {% endif %} {% if not request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:register' %}">Register</a>
        </li>
        {% endif %}
       
      </ul>
      <form action="{% url 'hotel:searchhotel' %}" method="post" class="d-flex">
        {% csrf_token %}
        <input
          class="form-control me-2"
          type="search"
          placeholder="Hotel Name or Address"
          aria-label="Search"
          name="searchtext"
        />
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

templates/terms.html
{% extends 'base.html' %}

{% block content %} 
{% include 'navbar.html' %}
<h1>Terms and Conditions</h1>
<p>1. Payment is required in advance as per the hotel's rates and policies.</p>
<p>2. A valid credit card or payment method must be provided to secure a booking.</p>
<p>3. Cancellations must be made in accordance with the hotel's cancellation policy. Late cancellations or no-shows may result in charges. Please refer to our cancellation policy for details.</p>
<p>4. Check-in time is 5:00 AM, and check-out time is 12:00 PM. Early check-in and late check-out may be available upon request and subject to availability.</p>
<p>5. The Hotel will make every effort to accommodate your room preferences. However, room assignments are subject to availability and cannot be guaranteed.</p>
<p>6. Pets are not allowed on the premises, with exceptions made for service animals as required by law.</p>
<p>7. Guests are responsible for any damages or losses caused to hotel property during their stay, and charges may be applied to their account.</p>
<p>8. Guests are expected to conduct themselves in a respectful and considerate manner. Excessive noise or disruptive behavior may result in eviction without a refund</p>
<p>9. The Hotel is not liable for any injuries, accidents, or losses incurred by guests during their stay.</p>
<p>10. The Hotel respects guest privacy and complies with applicable data protection laws.</p>
<p>11. The Hotel shall not be liable for any failure to perform its obligations due to circumstances beyond its control, including but not limited to natural disasters, acts of terrorism, or government restrictions.</p>
<p>12. The Hotel reserves the right to modify these terms and conditions at any time. The most current version will be available on our website or provided upon request.</p>
<h1>Cancellation Policy</h1>
<p>1. 20% cancellation charge apply for every booking if cancelled.</p>
<p>2. No-shows made on the day of arrival will be charged for the full reservation amount.</p>
<br>
<p>By making a reservation with us you agree to abide by these terms and conditions.</p>

{% endblock content %}